[add] run s2p on remote images (/vsicurl/http://..)
MISS3D/s2p pull request #145
Opened 2018-02-21 14:59 UTC by gfacciol

This PR adds support for reading the RPC from remote image through vsicurl. 
Now we can seamlessly run s2p on images from internet.

2018-03-05 14:22 UTC, jmichel-otb commented on s2plib/initialization.py
> +    print (d)
Is this print mandatory or it is a trace left for debuging ?

2018-03-05 14:22 UTC, jmichel-otb commented on s2plib/rpc_utils.py
> +        if(1):
if(1) always true

2018-03-05 14:23 UTC, jmichel-otb requested changes
Two minor comments

2018-03-05 19:06 UTC, gfacciol commented on s2plib/initialization.py
> +    print (d)
it was a debug leftover, I'm fixing it.

2018-03-06 09:34 UTC, jmichel-otb approved these changes

2018-03-06 09:40 UTC, merged