Better testing
MISS3D/s2p pull request #44
Opened 2017-02-07 12:45 UTC by jmichel-otb

Adds a triplet test case and improves a bit s2p_test.py.

2017-02-07 14:59 UTC, jmichel-otb commented
I do not know what to do with the reference dsm : the test pass on my computer

2017-02-09 14:41 UTC, carlodef reviewed
Hi,
I think that commit bcd9b27b26614b97d0f768e65609c41fc314c4e9 should not be on this branch (it should not be part of this pull request). Each pull request should have a single purpose and be as short as possible. Here we are mixing improvements of the test system with an enhancement of the algorithm.

2017-02-10 10:01 UTC, jmichel-otb commented
Note : This last failed check is not related to the PR but to an error in the travis build (for some reason adding ubuntugis ppa fails).

2017-02-10 10:39 UTC, mnhrdt commented
This is a normal occurrence.   The url of this ppa is offline from time to time, and the build fails.  You can re-launch the test from the web interface of travis associated to your fork.

2017-02-10 12:01 UTC, dyoussef approved these changes

2017-02-10 14:25 UTC, jmichel-otb commented
Is there something blocking a positive review of this PR ? The more we wait the more it gets out of sync with master, plus we really need this as a solid basis for future PR.

2017-02-10 14:28 UTC, carlodef commented
I'm out of office today.

Le 10 févr. 2017 15:25, "Julien Michel" <notifications@github.com> a écrit :

Is there something blocking a positive review of this PR ? The more we wait
the more it gets out of sync with master, plus we really need this as a
solid basis for future PR.

—
You are receiving this because your review was requested.

Reply to this email directly, view it on GitHub
<https://github.com/MISS3D/s2p/pull/44#issuecomment-278953813>, or mute the
thread
<https://github.com/notifications/unsubscribe-auth/AD9EywV-T0lSSRsqwFkR83R1B15VnZjzks5rbHNggaJpZM4L5cae>
.

2017-02-15 17:32 UTC, carlodef requested changes
Thank you for this pull request.

I mostly agree with it, except for these specific points (highlighted in the code below):
* the first unit test on sift is too restrictive
* the patch to ensure that RPC computation are done in double precision is useless as Python floats use double precision
* the fix in plyflatten was submitted in pull request #46 (see the requested changes). It can be merged separately, however.
* the "sifts from neighborhood" fix could have been isolated in a separate pull request

2017-02-15 17:32 UTC, carlodef commented on s2plib/rpc_model.py
> +                if   a[0] == "LINE":   self.linOff = np.float64(val)
these changes are not necessary as Python floats are represented with IEEE 754 double precision:

https://docs.python.org/3.0/tutorial/floatingpoint.html

> Almost all machines today (November 2000) use IEEE-754 floating point arithmetic, and almost all platforms map Python floats to IEEE-754 “double precision”

2017-02-15 17:32 UTC, carlodef commented on s2plib/initialization.py
> +            for y2 in [ry - th, ry, ry + th]:
I think there's an error here: it should be `for y2 in [y - th, y, y + h]:`

2017-02-15 17:32 UTC, carlodef commented on s2plib/initialization.py
> +                for x2 in [rx - tw, rx, rx + tw]:
Same error here: `for x2 in [x - tw, x, x + w]:`

2017-02-15 17:32 UTC, carlodef commented on s2plib/initialization.py
> +                    if rx + rh >= x2 >= rx:
I think that`rw` and `rh` got mixed in this line and the next

2017-02-15 17:32 UTC, carlodef commented on s2plib/initialization.py
> +                    if rx + rh >= x2 >= rx:
The first comparison should be strict: `if rx + rw > x2 >= rx:`

2017-02-15 17:32 UTC, carlodef commented on s2plib/initialization.py
> +                        if ry + rw >= y2 >= ry:
replace `rw` with `rh`

2017-02-15 17:32 UTC, carlodef commented on s2p_test.py
> +    print(str(test_kpts.shape[0]-len(test_set))+" duplicate kpts found in test")
Why calling "duplicates" keypoints that have the same x, y coordinates? They probably have different scales and/or orientations.

2017-02-15 17:32 UTC, carlodef commented on s2p_test.py
> +    np.testing.assert_equal(nb_ref_not_in_test,0)
This seems too restrictive. Detections that were very close to some threshold may appear or disappear depending on the machine. Having 90% of the keypoints at less that 0.01 pix should be fine.

2017-02-15 17:32 UTC, carlodef commented on s2p_test.py
> +    s2plib.config.cfg['disable_srtm'] = False
why?

2017-02-20 09:04 UTC, jmichel-otb commented on s2plib/rpc_model.py
> +                if   a[0] == "LINE":   self.linOff = np.float64(val)
I can backout this change if necessary. However, I read the same article but see no arm in trading "almost all machines" for "all machines".

2017-02-20 09:05 UTC, jmichel-otb commented on s2p_test.py
> +    print(str(test_kpts.shape[0]-len(test_set))+" duplicate kpts found in test")
I can change it to spatial duplicates because this is what we check here. The idea of this test is to know better what exactly are the differences of sift between integration configurations.

2017-02-20 09:09 UTC, jmichel-otb commented on s2p_test.py
> +    np.testing.assert_equal(nb_ref_not_in_test,0)
I do not agree with you. If we want efficient testing we need to set the threshold as tight as possible while getting the tests to pass on all CI configurations. This is the only way to spot small changes that may have great impact downstream. There might be only one or two more keypoints but if those keypoints widen the disparity range the difference end to end might be huge, and we want to know what causes the change.

The current test requirement passes on all CI configurations. If and when this changes, we will lower the expectation after a careful analysis of the impact.

2017-02-20 09:10 UTC, jmichel-otb commented on s2p_test.py
> +    s2plib.config.cfg['disable_srtm'] = False
This is no longer needed since configuration is reset for each test. Will remove it.

2017-02-20 13:19 UTC, closed without merging