fixed plyflatten
MISS3D/s2p pull request #46
Opened 2017-02-08 15:13 UTC by dyoussef

[bug] fixed rescale_float_to_int
- the points that are out of the image are rejected
- rescale_float_to_int uses directly the resolution parameter

2017-02-10 11:42 UTC, mnhrdt reviewed
what is the meaning of the variable "resolution" ?

2017-02-10 12:16 UTC, dyoussef commented
The variable "resolution" corresponds to the input parameter "resolution". Did it answer your question?

2017-02-15 15:26 UTC, carlodef requested changes
Could you commit the correct dsm.tif produced with this fix on the test case, so that the Travis tests pass?

2017-02-15 15:26 UTC, carlodef commented on c/plyflatten.c
>  // re-scale a float between 0 and w
this comment doesn't match the code

2017-02-15 15:26 UTC, carlodef commented on c/plyflatten.c
> +				     float xmin, float xmax, float ymin, float ymax, float resolution,
this function has now two unused arguments: xmax and ymin

2017-02-15 15:26 UTC, carlodef commented on c/plyflatten.c
> +				     char utm_zone[3], char *fname, int col_idx)
this file was indented with tabs but you used spaces. The indentation is now mixed.

2017-02-15 15:26 UTC, carlodef commented on c/plyflatten.c
> +        int r = (int) (round((x-min)/resolution));
I agree with using round instead of floor (it implies that the geographic coordinates xmin, ymax stored in the geotif header are those of the center of the top-left pixel).

For consistency, the size of the image should also be computed with round.

2017-02-15 16:07 UTC, dyoussef commented on c/plyflatten.c
> +        int r = (int) (round((x-min)/resolution));
I think the geographic coordinates xmin, ymax stored in the geotif header are those of the top left corner of the top-left pixel. So I will replace round by floor.

2017-02-15 16:14 UTC, dyoussef commented on c/plyflatten.c
> +        int r = (int) (round((x-min)/resolution));
and therefore :
// compute output image dimensions
int w = (xmax - xmin) / resolution;
int h = (ymax - ymin) / resolution;

2017-02-15 19:24 UTC, carlodef commented on c/plyflatten.c
> +        int r = (int) (round((x-min)/resolution));
When x = xmax, the col index of the pixel you want to access is exactly `(int) (xmax - xmin) / resolution`. Thus the width of the image has to be at least `1 + (xmax - xmin) / resolution`

2017-02-15 20:32 UTC, dyoussef commented on c/plyflatten.c
> +        int r = (int) (round((x-min)/resolution));
If x = xmax, the point is out of the image (w+1)

2017-02-15 22:01 UTC, carlodef commented on c/plyflatten.c
> +        int r = (int) (round((x-min)/resolution));
This is not the desired behaviour. We want a tool that projects all the input points on a raster DSM. The width and height of the raster have to be large enough to contain all the projected points.

2017-02-16 06:27 UTC, dyoussef commented on c/plyflatten.c
> +        int r = (int) (round((x-min)/resolution));
So the extrema values are incorrectly calculated :
xmin = xmin - resolution/2
xmax = xmax + resolution/2
ymin = ymin - resolution/2
ymax = ymax + resolution/2

2017-02-16 07:33 UTC, carlodef commented on c/plyflatten.c
> +        int r = (int) (round((x-min)/resolution));
???

2017-02-16 08:12 UTC, dyoussef commented on c/plyflatten.c
> +        int r = (int) (round((x-min)/resolution));
(xmin, ymax) : coordinates the top left corner of the top-left pixel
(xmax, ymin) : coordinates the bottom right corner of the bottom right pixel.
(cf. http://www.gdal.org/gdal_datamodel.html)
I close the pull request to make changes.

2017-02-17 10:49 UTC, closed without merging