Fix plyflatten
MISS3D/s2p pull request #54
Opened 2017-02-17 13:20 UTC by dyoussef

- the points that are out of the image are rejected
- rescale_double_to_int uses directly the resolution parameter
- conventions : (xmin, xmax, ymin, ymax) is the bounding box of the input points clouds and (xoff, xoff+xsize*resolution, yoff, yoff+ysize*resolution) are the output image corners ((xoff, yoff) : the top left corner of the top-left pixel and (xoff+xsize*resolution, yoff+ysize*resolution) : the bottom right corner of the bottom right)
- modified plyflatten interface : bb -> srcwin
- float -> double

2017-02-20 12:23 UTC, jmichel-otb approved these changes
Changing bbox for src_win avoids ambiguous definition of the image grid.

2017-02-21 00:39 UTC, carlodef requested changes
Thank you very much David for this neat pull request. I agree with it but I don't see the point of changing float to double.

2017-02-21 00:39 UTC, carlodef commented on c/plyflatten.c
> +	        double xmiddle = (xmax + xmin) / 2.0;
variables xmiddle and ymiddle are not used and could be removed.

2017-02-21 00:39 UTC, carlodef commented on c/plyflatten.c
> +	x.min = xmalloc(xsize*ysize*sizeof(double));
is that necessary to store altitudes as doubles? It will make plyflatten use twice more memory, which is a concern when producing a single dsm file from a large collection of ply files (for a full Pléiades scene for instance)

2017-02-21 00:39 UTC, carlodef commented on c/plyflatten.c
> +	iio_save_image_double(filename_out, x.avg, xsize, ysize);
I don't think that storing the output dsm as doubles gives more accuracy. But it makes the output file twice as heavy, which I'd like to avoid given that these files are usually pretty heavy even with floats.

2017-02-21 00:39 UTC, carlodef commented on c/plyflatten.c
> +		xsize = 1 + ceil((xmax - xmin) / resolution);
if we use ceil instead of floor I think that the +1 is not necessary

2017-02-21 10:14 UTC, dyoussef commented on c/plyflatten.c
> +	        double xmiddle = (xmax + xmin) / 2.0;
Done

2017-02-21 10:14 UTC, dyoussef commented on c/plyflatten.c
> +	x.min = xmalloc(xsize*ysize*sizeof(double));
It's necessary to store positions as double but altitudes can be stored as float, you are right.
I changed it

2017-02-21 10:15 UTC, dyoussef commented on c/plyflatten.c
> +	iio_save_image_double(filename_out, x.avg, xsize, ysize);
Same remark as above

2017-02-21 10:23 UTC, jmichel-otb approved these changes

2017-02-21 13:47 UTC, carlodef approved these changes

2017-02-21 13:50 UTC, merged